services:
  bot:
    container_name: "bot"
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 bot.py
    volumes:
      - .:/bot
    env_file:
      - .env
    networks:
      - crm_network
networks:
  crm_network:
    external: true